{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-helm.name" . }}-config
  labels:
    {{- include "nginx-helm.labels" . | nindent 4 }}
data:
  nginx.conf: |
    {{- .Values.configMap.nginx.conf | nindent 4 }}
{{- end }}