apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-helm.name" . }}
  labels:
    {{- include "nginx-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-helm.selectorLabels" . | nindent 8 }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "nginx-helm.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          {{- if .Values.resources.enabled }}
          resources:
            {{- if .Values.resources.limits }}
            limits:
              {{- toYaml .Values.resources.limits | nindent 14 }}
            {{- end }}
            {{- if .Values.resources.requests }}
            requests:
              {{- toYaml .Values.resources.requests | nindent 14 }}
            {{- end }}
          {{- end }}
          {{- if .Values.configMap.enabled }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          {{- end }}
      {{- if .Values.configMap.enabled }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "nginx-helm.name" . }}-config
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}